### ISSUE TITLE
enhancement: add default values in tags

### ISSUE THREAD

**Issue by art-frela** [kaatinga/settings#4]
```go
type settings struct {
	Port       string `env:"PORT" validate:"numeric" default_env:"8080"`
	Database   string `env:"DATABASE" default_env:"postgres://postgres:test@localhost:5432/postgres?sslmode=disable "`
	CacheSize  byte   `env:"CACHE_SIZE"`
	LaunchMode string `env:"LAUNCH_MODE" default_env:"stage"`
}
```

If my config will be consist of 100500 fields, then I must set all of those env variables? No, thanks! Better I will be use another env package...

P.S. name of the package not go convention I think (env_loader.<Method>... ;-) )

**Comment by kaatinga** [comment]
agree, have not decided yet how to rename

**Comment by kaatinga** [comment]
v1.3.0, added the default tag

**Comment by kaatinga** [comment]
package is called settings now
